services:
  db:
    image: postgres:15
    container_name: afc_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: api/Dockerfile

    container_name: afc_api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
  
  etl:
    build:
      context: .
      dockerfile: etl/Dockerfile
    container_name: afc_etl
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./data:/app/data
      
  metabase:
    image: metabase/metabase:latest
    container_name: afc_metabase
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  test:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: pytest
    depends_on:
      - db
      
volumes:
  postgres_data:
  metabase_data: